name: Compile changelogs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CompileCL:
    runs-on: ubuntu-latest
    if: github.repository == 'Lorwp/ChangelogGenStation' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Otherwise, we will fail to push refs
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml bs4
      - name: Compile CL
        run: |
          git checkout -f dev
          git reset --hard origin/dev
          python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --local user.email "80083319+BS12Changelogs@users.noreply.github.com"
          git config --local user.name "BS12Changelogs"
          git commit -m "Automatic changelog generation" -a
          git push https://${{ secrets.BOT_TOKEN }}:x-oauth-basic@github.com/Baystation12/Baystation12.git dev